version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=fidiscanner_db
      - DB_PORT=3306
    depends_on:
      - mysql
    networks:
      - my-network
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fidiscanner_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    networks:
      - my-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
volumes:
  mysql_data: